FROM selenium/standalone-chrome-debug:latest
   
# Copy an edited startup script that includes arguments 
# needed for performance metric testing via devtools.
COPY google-chrome /opt/google/chrome/google-chrome
